apps/article/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('<int:article_id>/',views.article_detail,name='article_detail'),
    path('login/',views.logon_view,name='login'),
    path('lognup/',views.lognup_view,name='lognup'),
    path('article_list/',views.article_list,name='article_list'),
    path('public_comment/',views.public_comment,name='public_comment'),

]

apps/mosiauth/urls.py
from django.urls import path
from . import views

app_name = 'mosiauth'

urlpatterns = [
    path('loginsss/', views.login_view, name='loginsss'),
    path('logout/',views.logout_view,name='logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
    path('register/',views.register,name='register'),

]

mosiblog/urls.py
from django.urls import path,include
from apps.article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('article/',include("apps.article.urls")),
    path('msauth/',include("apps.mosiauth.urls")),
    path('cms/',include("apps.cms.urls")),
    path('ueditor/',include('apps.ueditor.urls')),
    path('videocourse/',include('apps.videocourse.urls')),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/article/models.py
from django.db import models


# 分类模型
class ArticleCategory(models.Model):
    name = models.CharField(max_length=100)



# 文章模型
class Article(models.Model):
    # 标题
    title = models.CharField(max_length=200)
    # 描述信息
    desc = models.CharField(max_length=200)
    # 缩略图
    thumbnail = models.URLField()
    # 文本编辑器里面的内荣
    content = models.TextField()
    # 发布事件
    pub_time = models.DateTimeField(auto_now_add=True)
    # 分类 ,ForeignKey是一对多的关系
    category = models.ForeignKey('ArticleCategory',on_delete=models.SET_NULL,null=True)
    # 作者
    author = models.ForeignKey('mosiauth.User',on_delete=models.SET_NULL,null=True)
    # 观看数量
    look_quantity = models.CharField(max_length=100)
    # 评论数量
    comment = models.CharField(max_length=100)

    class Meta:
        # 时间排序
        ordering = ['-pub_time']



# 评论模型
class Comment(models.Model):
    # 用户名
    # CASCADE级联删除。当删除'一'时，‘多’会被删除。
    # 用户被删除掉了，那么这个评论也就会被删除
    author = models.ForeignKey("mosiauth.User", on_delete=models.CASCADE)
    # 评论的内容
    content = models.TextField()
    # 评论时间
    pub_time = models.DateTimeField(auto_now_add=True)
    # 文章 (哪一篇文章), 使用级联删除，新闻被删除，评论也会被删除
    article = models.ForeignKey('Article',on_delete=models.CASCADE,related_name='comments')

    class Meta:
        ordering = ['-pub_time']

apps/article/forms.py
from django import forms
from apps.forms import FormMixin




# 验证评论内容与文章id的表单
class PublicCommentForm(forms.Form,FormMixin):

    content = forms.CharField()
    article_id = forms.IntegerField()

apps/article/views.py
from django.shortcuts import render
from .models import ArticleCategory,Article,Comment
from django.conf import settings
from .serializers import ArticleSerializer,CommentSerizlizer
from utils import restful
from .forms import PublicCommentForm
from apps.mosiauth.decorators import blog_login_required


# 主页视图函数
def index(request):

    count = settings.ONE_PAGE_NEWS_COUNT

    # select_related提前查找外键，提高sql查询性能（外键都能以这种形式来运行）
    acrticles = Article.objects.select_related('category','author').all()[0:count]
    categories = ArticleCategory.objects.all()
    # 随机抽取12条给推荐内容
    results = Article.objects.order_by('?')[:12]
    article_recommend = list(results)
    context = {
        'categories': categories,
        'acrticles' :acrticles,
        'article_recommend':article_recommend
    }
    return render(request,'article/index.html',context=context)


# 文章详细页视图函数
def article_detail(request,article_id):
    # 获取pk, 内容等于传进来的id
    # select_related提前查找外键，提高sql查询性能（外键都能以这种形式来运行）
    articles = Article.objects.select_related('category','author').get(pk=article_id)

    # 随机抽取6条给热门内容
    results = Article.objects.order_by('?')[:6]
    article_recommend = list(results)
    context = {
        'articles': articles,
        'article_recommend':article_recommend
    }

    return render(request,'article/article_detail.html',context=context)


# 登陆页面视图函数
def logon_view(request):
    return render(request,'article/login.html')

# 注册页面视图函数
def lognup_view(request):
    return render(request,'article/register.html')


# 文章列表（点击加载更多部分）
def article_list(request):
    # 1.获取页数p, 默认方式页数为1，
    page = int(request.GET.get('p',1))

    # 获取分类的Id,默认id=0,等于0就等于不分类
    category_id = int(request.GET.get('category_id',0))


    # 假设ONE_PAGE_NEWS_COUNT = 5
    # 如果传进来的是1，其实值则是0，结束值是5那么就是0：5之间的数据
    # page = 1 的时候 start0：end5
    # page = 2 的时候，start5:end10
    # page = 3的时候 ，start10:end15
    # page由前端传入，每点击一次的时候page加1

    # 起始页数
    start = (page-1)*settings.ONE_PAGE_NEWS_COUNT
    # 结束页数
    end = start + settings.ONE_PAGE_NEWS_COUNT

    # 如果分类等于0
    if category_id == 0:
        # 取值
        # select_related提前查找外键，提高sql查询性能（外键都能以这种形式来运行）
        article = Article.objects.select_related('category','author').all()[start:end]

    else:

        # 实验是否需要两个下划线
        # 提取出所有相关id的内容
        # select_related提前查找外键，提高sql查询性能（外键都能以这种形式来运行）
        article = Article.objects.select_related('category','author').filter(category__id=category_id)[start:end]
    # 进行序列化操作
    serializers = ArticleSerializer(article,many=True)
    # 取出data值
    data = serializers.data

    return restful.result(data=data)

# 发表评论
@blog_login_required
def public_comment(request):
    form  = PublicCommentForm(request.POST)
    if form.is_valid():
        article_id = form.cleaned_data.get('article_id')
        content = form.cleaned_data.get('content')
        article = Article.objects.get(pk=article_id)
        comment = Comment.objects.create(content=content,article=article,author=request.user)
        serizlize = CommentSerizlizer(comment)
        return restful.result(data=serizlize.data)
    else:
        return restful.params_error(message=form.get_errors())

front/templates/article/article_detail.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title %}
{{ articles.title }}
{% endblock %}



{% block head %}

    <script src="{% static 'js/article_detail.min.js' %}"></script>
     <script src="{% static 'arttemplate/template-web.js' %}"></script>


    <script id="comment-item" type="text/html">
    {% verbatim %}
    <li>
        <div class="comment-info">
            <img src=https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=1486417265,2302447757&fm=58&bpow=1200&bpoh=1600" alt="" class="avatar">
            <span class="author">{{ comment.author.username }}</span>
            <span class="pub-time">{{ comment.pub_time|timeSince }}</span>
        </div>
        <p class="comment-content">{{ comment.content }}</p>
    </li>
    {% endverbatim %}
    </script>



{% endblock %}


{% block container %}
<div class="container">
    <div class="col-md-8">
      <span class="news-title">

          <h1>{{ articles.title }}</h1>

          </span>
      <div class="news-status">{{ articles.look_quantity }}阅读 • {{ articles.pub_time|time_since }}发布
        <div class="label label-default">{{ articles.category.name }}</div>

      </div>
      <div class="news-content">
        <blockquote>
          <p>
            {{ articles.desc }}
          </p>
        </blockquote>

          {{ articles.content|safe }}

      </div>


        <div class="comment-wrapper">
            <h3 class="title">文章评论（{{ articles.comments.count }}）</h3>
            <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
            <div class="submit-btn-group">
                <button class="btn btn-primary submit-btn" data-news-id="{{ articles.pk }}">立即评论</button>
            </div>
            <ul class="comment-list">
                    {% for comment in articles.comments.all %}
                      <li>
                        <div class="comment-info">
                            <img src="https://ss2.baidu.com/6ONYsjip0QIZ8tyhnq/it/u=1486417265,2302447757&fm=58&bpow=1200&bpoh=1600" alt="" class="avatar">
                            <span class="author">{{ comment.author.username }}</span>
                            <span class="pub-time">{{ comment.pub_time|time_since }}</span>
                        </div>
                        <p class="comment-content">{{ comment.content }}</p>
                      </li>

                 {% endfor %}

            </ul>
        </div>





    </div>


    <div class="col-md-4">

        <div class="main">

      <div class="side-bar-card">

        <div class="card-title">相关推荐</div>
        <div class="card-body">


          <div class="list">



    {% for recommend in article_recommend %}
            <div class="item clearfix">
              <div class="col-xs-5 no-padding-h">
                <img src="{{ recommend.thumbnail }}">
              </div>
              <div class="col-xs-7">


                  <a href="{% url 'article:article_detail' article_id=recommend.pk %}">

                      <div class="title">{{ recommend.title }}</div>
                        <div class="desc">{{ recommend.look_quantity }}阅读 {{ recommend.comments.count }}评论</div>

                  </a>
              </div>
            </div>
                {% endfor %}

          </div>
        </div>
      </div>


        </div>
    </div>
  </div>
{% endblock %}

front/templates/article/index.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title %}
博客首页
{% endblock %}





{% block head %}
    <script src="{% static 'js/index.min.js' %}"></script>
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script id="news-item" type="text/html">
        {% verbatim %}
        {{ each articles article i}}
          <div class="news-list-item clearfix">
            <div class="col-xs-4">
              <img src="{{ article.thumbnail}}">
            </div>
            <div class="col-xs-8">
              <a href="/article/{{ article.id }}" class="title">{{ article.title }}</a>

              <div class="info">
                <span><span class="avatar"></span>{{ article.category.name }}</span> ⋅
                <span>{{ article.look_quantity}}人看过</span> ⋅
                <span>{{ article.pub_time|timeSince}}</span>
              </div>
            </div>
          </div>


        {{ /each }}
        {% endverbatim %}
</script>

{% endblock %}





{% block container %}
<div class="container">
    <div class="row">
      <div class="col-sm-2">
        <div class="hidden-xs list-group side-bar category-group">
          <a data-category="0" href="javascript:void(0);" class="list-group-item active">最新文章</a>
            {% for category in categories %}
          <a data-category="{{ category.pk }}" href="javascript:void(0);" class="list-group-item">{{ category.name }}</a>
             {% endfor %}
        </div>
      </div>


      <div class="col-sm-7">
        <div class="news-list">

            {% for acrticle in acrticles %}

          <div class="news-list-item clearfix">
            <div class="col-xs-4">
              <img src="{{ acrticle.thumbnail }}">
            </div>
            <div class="col-xs-8">
              <a href="{% url 'article:article_detail' article_id=acrticle.pk %}" class="title">{{ acrticle.title }}</a>

              <div class="info">
                <span><span class="avatar"></span>{{ acrticle.category.name }}</span> ⋅
                <span>{{ acrticle.look_quantity}}人看过</span> ⋅
                <span>{{ acrticle.comments.count}}评论</span> ⋅
                <span>{{ acrticle.pub_time|time_since }}</span>
              </div>
            </div>
          </div>

            {% endfor %}




        </div>
        <div class="buttom-group">

        <button class="btn btn-primary btn-block submitbtn" type="submit">更多</button>
      </div>


      </div>
      <div class="col-sm-3">
{#        <div class="search-bar">#}
{#          <input type="search" class="form-control" placeholder="搜索">#}
{#        </div>#}


       <div class="input-group">
          <input type="text" class="form-control" name="search" placeholder="python之美">
          <div class="input-group-btn">
            <div class="btn btn-primary search-btn"><b>搜索</b></div>
          </div>
        </div>
{#        <div class="side-bar-card flag clearfix">#}
{##}
{#            <div class="text-lg">微信赞助</div>#}
{#            <img src="{% static 'images/微信图片_20181205155247.jpg' %}">#}
{#          </div>#}

        <div class="side-bar-card">
          <div class="card-title">热门文章</div>
          <div class="card-body">
            <div class="list">

                {% for recommend in article_recommend %}







              <div class="item">


                  <a href="{% url 'article:article_detail' article_id=recommend.pk %}"><div class="title">{{ recommend.title }} </div></a>


                      <div class="desc">{{ recommend.look_quantity }}阅读 {{ recommend.comments.count }}评论</div>



              </div>

         {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

front/templates/article/login.html
{% extends 'base/front_base.html' %}


{% block title %}
磨斯博客登陆页
{% endblock %}
{% block head %}
 <script src="{% static 'js/auth.min.js' %}"></script>
{% endblock %}

{% block container %}
  <div class="container container-small">

    <h1>登录
      <small>没有账号？<a href="#">注册</a></small>
    </h1>
      <div class="form-group">
        <label>手机号码</label>
        <input type="text" class="form-control" name="telephone">
      </div>
      <div class="form-group">
        <label>密码</label>
        <input type="password" class="form-control" name="password">
      </div>

    <div class="form-group">
        <label class="remember-label">
            <input type="checkbox" name="remember" value="1">
            记住我
        </label>
    </div>

      <div class="form-group">
        <button class="btn btn-primary btn-block submit-btn" type="submit">登录</button>
      </div>
      <div class="form-group">
        <a href="#">忘记密码？</a>

      </div>
  </div>
{% endblock %}

front/templates/article/register.html
{% extends 'base/front_base.html' %}

{% block title %}
磨斯博客注册页
{% endblock %}


{% block head %}
 <script src="{% static 'js/auth.min.js' %}"></script>
{% endblock %}


{% block container %}
  <div class="container container-small">
    <h1>注册
      <small>没有账号？<a href="#">注册博客</a></small>
    </h1>
    <form>
      <div class="form-group">
        <label>手机号码</label>
        <input type="text" class="form-control" name="telephone">
      </div>

        <div class="form-group">
        <label>用户名</label>
        <input type="text" class="form-control" name="username">
        </div>


        <div class="from-group">

        <div class="short-input-group">
             <label>图形验证码</label>
            <input type="text" class="form-control" name="images_captcha">
        </div>
        <div class="input-group-addon">
            <img src="{% url 'mosiauth:img_captcha' %}" alt="" class="img-captcha" style="cursor: pointer">
        </div>

        </div>



      <div class="form-group">
        <label class="password">密码</label>
        <input type="password" class="form-control" name="password1">
      </div>
        <div class="form-group">
        <label>确认密码</label>
        <input type="password" class="form-control" name="password2">
      </div>



      <div class="form-group">
        <label>验证码</label>
        <div class="input-group">
          <input type="text" class="form-control" name="sms_captcha">
          <div class="input-group-btn">
            <div class="btn btn-default sms-captcha-btn">获取验证码</div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <button class="btn btn-primary btn-block signup-btn" type="submit">注册</button>
      </div>
      <div class="form-group">
        注册磨斯博客即代表您同意<a href="#">磨斯博客服务条款</a>
      </div>
    </form>




  </div>

{% endblock %}