apps/article/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('<int:article_id>/',views.article_detail,name='article_detail'),
    path('login/',views.logon_view,name='login'),
    path('lognup/',views.lognup_view,name='lognup'),
    path('article_list/',views.article_list,name='article_list'),
    path('public_comment/',views.public_comment,name='public_comment'),

]

apps/cms/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'cms'


urlpatterns = [
    path('cms_index/',views.cms_index,name='cms_index'),
    path('article_category/',views.article_category,name='article_category'),
    path('add_article_category/',views.add_acticle_category,name='add_article_category'),
    path('edit_article_category/',views.edit_article_category,name='edit_article_category'),
    path('delete_article_category/',views.delete_article_category,name='delete_article_category'),
    path('write_news/',views.WriteArticle.as_view(),name='write_news'),
    path('upload_file/',views.upload_file,name='upload_file'),
    path('article_list/',views.ArticleListView.as_view(),name='article_list'),
    path('edit_list/',views.EditArticleView.as_view(),name='edit_list'),
    path('delete_article/',views.delete_article,name='delete_article'),
]

mosiblog/urls.py
from django.urls import path,include
from apps.article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('article/',include("apps.article.urls")),
    path('msauth/',include("apps.mosiauth.urls")),
    path('cms/',include("apps.cms.urls")),
    path('ueditor/',include('apps.ueditor.urls')),
    path('videocourse/',include('apps.videocourse.urls')),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/cms/forms.py
from django import forms
from apps.forms import FormMixin
from apps.article.models import Article



# 编辑分类的表单
class EditArticleCategoryForm(forms.Form,FormMixin):
    pk = forms.IntegerField(error_messages={'required':'必须传入分类id'})
    name = forms.CharField(max_length=100)


# 发布文章的表单
class WriteArticleForm(forms.ModelForm,FormMixin):
    # 使用model.form来验证表单

    # 表单
    category = forms.IntegerField()
    class Meta:
        # 验证表单来自Article模型
        model = Article
        # 排除字段
        exclude = ['category','author','pub_time','comment']


# 编辑文章的表单
class EditArticleForm(forms.ModelForm,FormMixin):
    category = forms.IntegerField(error_messages={'required':'必须传入分类id'})
    pk = forms.IntegerField(error_messages={'required':'必须传入pk'})
    class Meta:
        model = Article
        exclude = ['category','author','pub_time','comment']

apps/cms/views.py
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic import View
from django.views.decorators.http import require_POST,require_GET
from utils import restful
from apps.article.models import ArticleCategory,Article
from .forms import EditArticleCategoryForm,WriteArticleForm,EditArticleForm
import os
from django.conf import settings
from django.views.generic import View
from django.core.paginator import Paginator
from datetime import datetime
from django.utils.timezone import make_aware
from urllib import parse
from django.db.models import Count
from apps.mosiauth.decorators import blog_login_required
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator






# cms首页
@staff_member_required(login_url='/')
def cms_index(request):
    return render(request,'cms/cms_index.html')



# 文章分类的模板
@require_GET
@permission_required(perm="article.add_articlecategory",login_url='/')
def article_category(request):
    # 一般的这个在柱模板进行映射
    # categories = ArticleCategory.objects.all()
    # 计算出分类文章的数量，返回给前端。（这其中还可以添加筛选条件），注释部分是添加了筛选条件的，前端只需要读取num_articles，即可得出文章数量
    # category_list = Category.objects.filter(article__created_time_gt=(2015, 1, 1)).annotate(
    #     num_articles=Count('article')).filter(num_articles__gt=0)
    categories = ArticleCategory.objects.all().annotate(num_articles=Count('article')).all()

    context= {

        'categories':categories
    }

    return render(request,'cms/article_category.html',context=context)


# 添加文章分类

@require_POST
@permission_required(perm="article.add_articlecategory",login_url='/')
def add_acticle_category(request):
    # 单个字段不写表单,直接取值
    name = request.POST.get('name')
    # 验证表单是否存在
    exists = ArticleCategory.objects.filter(name=name).exists()
    if not exists:
        ArticleCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在')



# 编辑文章分类
@require_POST
@permission_required(perm="article.change_articlecategory",login_url='/')
def edit_article_category(request):

    form = EditArticleCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            ArticleCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该分类不存在')
    else:
        return restful.params_error(message=form.get_errors())


# 删除分类
@require_POST
@permission_required(perm="article.delete_articlecategory",login_url='/')
def delete_article_category(request):
    pk = request.POST.get('pk')
    try:
        ArticleCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message='该分类不存在')


# 发布文章
@method_decorator(permission_required(perm="article.add_article",login_url='/'),name='dispatch')
class WriteArticle(View):
    # 处理get请求

    def get(self,request):
        categories = ArticleCategory.objects.all()
        context = {

            'categories': categories
        }
        return render(request,'cms/write_article.html',context=context)
    # 处理post请求
    def post(self,request):
        form = WriteArticleForm(request.POST)

        if form.is_valid():
            # 标题
            title = form.cleaned_data.get('title')
            # 描述信息
            desc = form.cleaned_data.get('desc')
            # 缩略图
            thumbnail = form.cleaned_data.get('thumbnail')
            # 主要内容
            content = form.cleaned_data.get('content')
            # 分类id
            category_id = form.cleaned_data.get('category')
            # 分类
            category = ArticleCategory.objects.get(pk=category_id)
            # 浏览数量
            look_quantity = form.cleaned_data.get('look_quantity')
            # 评论数量后期直接统计渲染到模板即可
            Article.objects.create(title=title,desc=desc,thumbnail=thumbnail,content=content,category=category,look_quantity=look_quantity,author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())





#文章管理
@method_decorator(permission_required(perm="article.change_article",login_url='/'),name='dispatch')
class ArticleListView(View):
    def get(self,request):


        # 从前端获取相关参数
        page = int(request.GET.get('p', 1))
        start = request.GET.get('start')
        end = request.GET.get('end')
        title = request.GET.get('title')
        # request.GET.get(参数,默认值)
        # 这个默认值是只有这个参数没有传递的时候才会使用
        # 如果传递了，但是是一个空的字符串，那么也不会使用默认值
        category_id = int(request.GET.get('category',0) or 0)


        # 查询文章信息
        # 外键提前查询
        articles = Article.objects.select_related('category','author')


        # 如果可以获取到开始时间与结束时间,根据前端的时间参数进行查询,得到查询后的结果进行返回
        if start or end:
            if start:
                start_date = datetime.strptime(start,'%Y/%m/%d')
            else:
                start_date = datetime(year=2018,month=6,day=1)
            if end:
                end_date = datetime.strptime(end,'%Y/%m/%d')
            else:
                end_date = datetime.today()
            articles = articles.filter(pub_time__range=(make_aware(start_date),make_aware(end_date)))


        # 如果获取到title信息,根据查询到的title信息进行查询
        if title:
            articles = articles.filter(title__icontains=title)

        # 如果获取到分类信息,根据查询到的title信息进行查询
        if category_id:
            articles = articles.filter(category=category_id)

        # 传递可便利的对象,10表示每页显示的数量
        paginator = Paginator(articles,10)
        page_obj = paginator.page(page)

        context_data = self.get_pagination_data(paginator, page_obj)

        # 返回一些相关的参数,便于前端进行判断
        context = {
            'categories': ArticleCategory.objects.all(),
            'articles': page_obj.object_list,
            'page_obj': page_obj,
            'paginator': paginator,
            'start': start,
            'end': end,
            'title': title,
            'category_id': category_id,
            'url_query': '&'+parse.urlencode({
                'start': start or '',
                'end': end or '',
                'title': title or '',
                'category': category_id or ''
            })
        }
        context.update(context_data)
        return render(request,'cms/article_list.html',context=context)

    # 获取页数的相关信息
    def get_pagination_data(self, paginator, page_obj, around_count=2):

        # 当前页
        current_page = page_obj.number
        # 总页数
        num_pages = paginator.num_pages

        # 左边是否需要出现三个点
        left_has_more = False
        # 右边是否需要出现三个点
        right_has_more = False

        if current_page <= around_count + 2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page - around_count, current_page)

        if current_page >= num_pages - around_count - 1:
            right_pages = range(current_page + 1, num_pages + 1)
        else:
            right_has_more = True
            right_pages = range(current_page + 1, current_page + around_count + 1)

        return {
            # left_pages：代表的是当前这页的左边的页的页码
            'left_pages': left_pages,
            # right_pages：代表的是当前这页的右边的页的页码
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages
        }



# 编辑文章
@method_decorator(permission_required(perm="article.change_article",login_url='/'),name='dispatch')
class EditArticleView(View):
    def get(self,request):

        # 跟着文章id获取到所有文章字段信息
        article_id = request.GET.get('article_id')
        article = Article.objects.get(pk=article_id)
        context = {
            'article': article,
            'categories': ArticleCategory.objects.all()
        }
        return render(request,'cms/write_article.html',context=context)

    def post(self,request):
        form = EditArticleForm(request.POST)
        if form.is_valid():
            print("成功否?")
            # 标题
            title = form.cleaned_data.get('title')
            # 描述信息
            desc = form.cleaned_data.get('desc')
            # 缩略图
            thumbnail = form.cleaned_data.get('thumbnail')
            # 主要内容
            content = form.cleaned_data.get('content')
            # 分类id
            category_id = form.cleaned_data.get('category')
            pk = form.cleaned_data.get("pk")
            # 分类
            category = ArticleCategory.objects.get(pk=category_id)
            # 浏览数量
            look_quantity = form.cleaned_data.get('look_quantity')
            # 评论数量后期直接统计渲染到模板即可
            Article.objects.filter(pk=pk).update(title=title,desc=desc,thumbnail=thumbnail,look_quantity=look_quantity,content=content,category=category)
            print("成功否?")
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())




@require_POST
@permission_required(perm="article.delete_article",login_url='/')
def delete_article(request):
    article_id = request.POST.get('article_id')
    Article.objects.filter(pk=article_id).delete()
    return restful.ok()



# 上传文件到服务器

@require_POST
@staff_member_required(login_url='index')
def upload_file(request):
    # 获取文件
    file = request.FILES.get('file')
    # 获取文件名
    name = file.name
    # 保存到指定的文件夹，文件夹路径需要在settings中进行配置
    with open(os.path.join(settings.MEDIA_ROOT,name),'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL+name)
    # http://127.0.1:8000/media/abc.jpg
    return restful.result(data={'url':url})

front/templates/cms/article_category.html
{% extends 'cms/cms_base.html' %}

{% block title %}
文章分类
{% endblock %}


{% block head %}
<script src="{% static 'js/article_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
<h1>新闻分类</h1>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary pull-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>

                        {% for category in categories %}


                                <tr data-pk="{{ category.pk }} " data-name="{{ category.name }}">
                                    <td>{{ category.name }}</td>
                                    <td>{{ category.num_articles}}</td>
                                    <td>
                                        <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                        <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                    </td>
                                </tr>

                        {% endfor %}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/article_list.html
{% extends 'cms/cms_base.html' %}
{% load news_filters %}
{% block title %}
文章管理
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap-datepicker/dist/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/cms/article_list.min.css' %}">
    <script src="{% static 'js/article_list.min.js' %}"></script>
{% endblock %}



{% block content-header %}
<h1>文章管理</h1>
{% endblock %}



{% block content %}

<div class="row">
<div class="col-md-12">
    <div class="box">
                <div class="box-header">
            <form action="" method="get" class="form-inline">
                <div class="form-group left-group">
                    <label for="">时间：</label>
                    {% if start %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly value="{{ start }}">
                    {% else %}
                        <input type="text" class="form-control" name="start" placeholder="起始时间" id="start-picker" readonly>
                    {% endif %}
                    <span>—</span>
                    {% if end %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly value="{{ end }}">
                    {% else %}
                        <input type="text" id="end-picker" class="form-control" name="end" placeholder="结束时间" readonly>
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="title-input">标题：</label>
                    {% if title %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字" value="{{ title }}">
                    {% else %}
                        <input type="text" class="form-control" name="title" id="title-input" placeholder="关键字">
                    {% endif %}
                </div>
                <div class="form-group left-group">
                    <label for="category-input">分类：</label>
                    <select name="category" id="" class="form-control">
                        {% if category_id == 0 %}
                            <option value="0" selected>所有分类</option>
                        {% else %}
                            <option value="0">所有分类</option>
                        {% endif %}
                        {% for category in categories %}
                            {% if category_id == category.pk %}
                                <option value="{{ category.pk }}" selected>{{ category.name }}</option>
                            {% else %}
                                <option value="{{ category.pk }}">{{ category.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group left-group">
                    <button class="btn btn-primary">查询</button>
                </div>
                <div class="form-group">
                    <a href="{% url 'cms:article_list' %}">清除查询</a>
                </div>
            </form>
        </div>
                 <div class="box-body">
                     <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>标题</th>
                        <th>分类</th>
                        <th>发布时间</th>
                        <th>作者</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>


                    {% for article in articles %}
                        <tr>
                            <td><a target="_blank" href="{% url 'article:article_detail' article_id=article.pk %}">{{ article.title }}</a></td>
                            <td>{{ article.category.name }}</td>
                            <td>{{ article.pub_time|time_format}}</td>
                            <td>{{ article.author.username }}</td>
                            <td>
                                <a href="{% url 'cms:edit_list' %}?article_id={{ article.pk }}" class="btn btn-info btn-xs">编辑</a>
                                <button class="btn btn-danger btn-xs delete-btn" data-news-id="{{ article.pk }}">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


            <div class="box-footer">
            <p class="pull-left">第{{ current_page }}/总共{{ num_pages }}页</p>
            <ul class="pagination pull-right">
                {#上一页#}
                {% if page_obj.has_previous %}
                    <li><a href="?p={{ page_obj.previous_page_number }}{{ url_query }}">上一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">上一页</a></li>
                {% endif %}

                {# 是否需要出现三个点 #}
                {% if left_has_more %}
                    <li><a href="?p=1">1</a></li>
                    <li><a href="javascript:void(0);">...</a></li>
                {% endif %}

                {# 左边的页码 #}
                {% for left_page in left_pages %}
                    <li><a href="?p={{ left_page }}{{ url_query }}">{{ left_page }}</a></li>
                {% endfor %}

                {# 当前的页面 #}
                <li class="active"><a href="?p={{ current_page }}{{ url_query }}">{{ current_page }}</a></li>

                {# 右边的页码 #}
                {% for right_page in right_pages %}
                    <li><a href="?p={{ right_page }}{{ url_query }}">{{ right_page }}</a></li>
                {% endfor %}

                {# 用来控制右边三个点 #}
                {% if right_has_more %}
                    <li><a href="javascript:void(0);">...</a></li>
                    <li><a href="?p={{ num_pages }}{{ url_query }}">{{ num_pages }}</a></li>
                {% endif %}

                {#下一页#}
                {% if page_obj.has_next %}
                    <li><a href="?p={{ page_obj.next_page_number }}{{ url_query }}">下一页</a></li>
                {% else %}
                    <li class="disabled"><a href="javascript:void(0);">下一页</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</div>
</div>



{% endblock %}

front/templates/cms/cms_base.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 磨斯管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    {#弹窗插件#}
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">
    <script src="{% static 'adminlte/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>
    {#弹窗插件#}`
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/msajax.min.js' %}"></script>
    <script src="{% static 'js/msalert.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>


    {% block head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>CMS</b></span>
            <!-- logo for regular state and mobile devices -->

            <span class="logo-lg"> <b>磨斯</b>后台管理系统</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{% static 'images/zhipaiwu.jpg' %}"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">何楠</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <img src="{% static 'images/zhipaiwu.jpg' %}"
                                     class="img-circle" alt="User Image">
                                <p>
                                    何楠
                                    <small>Python web开发工程师</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">个人中心</a>
                                </div>
                                <div class="pull-right">
                                    <a href="#" class="btn btn-default btn-flat">退出登录</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="首页">
                    <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
          </span>
                </div>
            </form>
            <!-- /.search form -->
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="active">
                    <a href="{% url 'cms:cms_index' %}">
                        <i class="fa fa-home"></i>
                        <span>首页</span>
                    </a>
                </li>
                <li class="header">文章管理</li>
                    <li>
                        <a href="{% url 'cms:article_category' %}">
                            <i class="fa fa-tag"></i>
                            <span>文章分类</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'cms:write_news' %}">
                            <i class="fa fa-edit"></i>
                            <span>发布文章</span>
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'cms:article_list' %}">
                            <i class="fa fa-list"></i>
                            <span>文章列表</span>
                        </a>
                    </li>
            </ul>
        </section>
    </aside>
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>

        <section class="content">
           {% block content %}{% endblock %}
        </section>
    </div>
    <footer class="main-footer">
        <strong>磨斯</strong>后台管理系统
    </footer>
</div>
</body>
</html>

front/templates/cms/cms_index.html
{% extends 'cms/cms_base.html' %}

{% block title %}
首页
{% endblock %}

{% block content-header %}
<h1>欢迎来到纸牌屋</h1>
{% endblock %}