apps/article/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('<int:article_id>/',views.article_detail,name='article_detail'),
    path('login/',views.logon_view,name='login'),
    path('lognup/',views.lognup_view,name='lognup'),
    path('article_list/',views.article_list,name='article_list'),
    path('public_comment/',views.public_comment,name='public_comment'),

]

apps/cms/urls.py
#encoding: utf-8
from django.urls import path
from . import views

app_name = 'cms'


urlpatterns = [
    path('cms_index/',views.cms_index,name='cms_index'),
    path('article_category/',views.article_category,name='article_category'),
    path('add_article_category/',views.add_acticle_category,name='add_article_category'),
    path('edit_article_category/',views.edit_article_category,name='edit_article_category'),
    path('delete_article_category/',views.delete_article_category,name='delete_article_category'),
    path('write_news/',views.WriteArticle.as_view(),name='write_news'),
    path('upload_file/',views.upload_file,name='upload_file'),
    path('article_list/',views.ArticleListView.as_view(),name='article_list'),
    path('edit_list/',views.EditArticleView.as_view(),name='edit_list'),
    path('delete_article/',views.delete_article,name='delete_article'),
]

apps/mosiauth/urls.py
from django.urls import path
from . import views

app_name = 'mosiauth'

urlpatterns = [
    path('loginsss/', views.login_view, name='loginsss'),
    path('logout/',views.logout_view,name='logout'),
    path('img_captcha/',views.img_captcha,name='img_captcha'),
    path('sms_captcha/',views.sms_captcha,name='sms_captcha'),
    path('register/',views.register,name='register'),

]

apps/videocourse/urls.py
from django.urls import path
from . import views

app_name = 'videocourse'

urlpatterns = [
    path('video_index/', views.video_index, name='video_index'),
]

mosiblog/urls.py
from django.urls import path,include
from apps.article import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.index,name='index'),
    path('article/',include("apps.article.urls")),
    path('msauth/',include("apps.mosiauth.urls")),
    path('cms/',include("apps.cms.urls")),
    path('ueditor/',include('apps.ueditor.urls')),
    path('videocourse/',include('apps.videocourse.urls')),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/article/index.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/msajax.min.js' %}"></script>

    <script src="{% static 'js/auth.min.js' %}"></script>
    <script src="{% static 'js/index.min.js' %}"></script>




  {% block head %}{% endblock %}
</head>
<body>
  <div class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <a href="{% url 'index' %}" class="navbar-brand"><b>磨斯</b>博客</a>
      </div>
      <label id="toggle-label" class="visible-xs-inline-block" for="toggle-checkbox">MENU</label>
      <input class="hidden" id="toggle-checkbox" type="checkbox">
      <div class="hidden-xs">
        <ul class="nav navbar-nav">

          <li class="active"><a href="/">首页</a></li>
          <li><a href="{% url 'videocourse:video_index' %}">在线视频</a></li>
          <li><a href="{% url 'videocourse:video_index' %}">文件下载</a></li>
          <li><a href="{% url 'videocourse:video_index' %}">关于</a></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
        <li class="dropdown">
                <a href="#" class="dropdown-toggle authenticated-box" data-toggle="dropdown"> {{ user.username }}<b class="caret"></b></a>
                <ul class="dropdown-menu">
                {% if user.is_staff %}
                    <li class="divider"></li>
                    <li><a href="{% url 'cms:cms_index' %}">后台管理</a></li>
                     {% endif %}
                    <li class="divider"></li>
                    <li><a href="{% url 'mosiauth:logout' %}">退出登陆</a></li>
                </ul>

            </li>

               {% else %}
          <li><a href="{% url 'article:login' %}">登录</a></li>
          <li><a href="{% url 'article:lognup' %}">注册</a></li>
             {% endif %}
        </ul>
      </div>
    </div>
  </div>
  {% block container %} {% endblock %}

  <div class="footer">
    © 2018 磨斯博客 , 部分文章转载于网络
  </div>

</body>
</html>